### ISSUE TITLE
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found  in CentOS after using FCD module

### ISSUE THREAD

**Issue by toushi68** [molecularsets/moses#40]
This is the error message:
------------------------------------
(moses-env) [trial0@xps8500 moses]$ python scripts/train.py organ --help
Traceback (most recent call last):
  File "scripts/train.py", line 5, in <module>
    import rdkit
  File "/home/trial0/anaconda3/envs/moses-env/lib/python3.6/site-packages/rdkit/__init__.py", line 2, in <module>
    from .rdBase import rdkitVersion as __version__
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/trial0/anaconda3/envs/moses-env/lib/python3.6/site-packages/rdkit/rdBase.so)
-------------------------------------
However, rdkit itself is working:
-------------------------------------
(moses-env) [trial0@xps8500 ~]$ python
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from __future__ import print_function
>>> from rdkit import Chem
>>> m = Chem.MolFromSmiles('Cc1ccccc1')
>>> m
<rdkit.Chem.rdchem.Mol object at 0x7f1e30b8bf80>
-----------------------------------
This under CentOS 7.6 after introducing the FCD module with pytorch 1.01. It looks this is not rdkit problem because ORGAN is still running under this env. without any problem. 
Any idea? Thanks!

**Comment by danpol** [comment]
Try running `sudo apt-get install libxrender1 libxext6`

**Comment by toushi68** [comment]
This is CentOS 7.6, the corresponding libXrender and libXext 86-64 libs are already installed. I also added i686 versions. but I still got the same problem.
I also noticed libstdc++.so.6 is a recently updated version
lrwxrwxrwx. 1 root root 19 Mar 20 07:10 /lib64/libstdc++.so.6 -> libstdc++.so.6.0.19

**Comment by toushi68** [comment]
Although /usr/lib64/ /lib64/libstdc++.so.6 doesn't have GLIBCXX_3.4.21. But anaconda3 has installed the library:
strings /home/trial0/anaconda3/envs/moses-env/x86_64-conda_cos6-linux-gnu/sysroot/lib/libstdc++.so.6 | grep GLIBCXX_3.4.21
GLIBCXX_3.4.21
GLIBCXX_3.4.21
So how can I redirect train.py to read the python libraries?

**Comment by toushi68** [comment]
This case can be closed. This problem can be avoided if we use conda to install pytorch for CentOs.
