### ISSUE TITLE
How to generate compounds from single smiles string?

### ISSUE THREAD

**Issue by abhik1368** [molecularsets/moses#41]
Can you help with the generation of compounds from a single smiles files ?

**Comment by abhik1368** [comment]
How to generate compounds from single smiles string? just now

**Comment by danpol** [comment]
@abhik1368, I'm not sure that I understand what "generation from a single smiles files" means. Could you please elaborate on this?

**Comment by abhik1368** [comment]
> @abhik1368, I'm not sure that I understand what "generation from a single smiles files" means. Could you please elaborate on this?

If i want to use  a simles string how can i generate compounds, which are the functions to encode and decode ?

**Comment by danpol** [comment]
If I understood you correctly, you want to manually call encode/decode functions for a trained model? For example, in AAE you can run `model.encoder(x)` and `model.decoder(x)` respectively. Here, `x` is one-hot encoding of a SMILES string. You can get it using [collate function](https://github.com/molecularsets/moses/blob/master/moses/aae/trainer.py#L235): `collate = aae_trainer.get_collate_fn(aae)`.  Then you can get `x` using `collate(list_of_smiles)`. In general, all code for doing this is similar to the [training loop](https://github.com/molecularsets/moses/blob/master/moses/aae/trainer.py#L107) of AAE model.

**Comment by abhik1368** [comment]
Ok i understand but how to generate a string from a latent space with specified standard deviation/noise . Just like in [chemvae](https://github.com/aspuru-guzik-group/chemical_vae/blob/b2eae7e5af8980f47dbb1555e6483fc86755ab73/examples/intro_to_chemvae.ipynb)

**Comment by danpol** [comment]
I think the function you are looking for is https://github.com/molecularsets/moses/blob/master/moses/aae/model.py#L138 — it samples molecules in a SMILES format. Currently, there is no way to directly specify the exact latent code for sampling.

**Comment by xuzhang5788** [comment]
@abhik1368 
I have the same question as you. Did you solve this problem? If yes, would mind sharing it? Many thanks

**Comment by abhik1368** [comment]
nope
