### ISSUE TITLE
value of FCD Test and FCD Test SF

### ISSUE THREAD

**Issue by xusworld** [molecularsets/moses#44]
When I trained char-rnn model on my  pc  and got 30,000 samples from this generative model. After I evalutated the results between [MOSES](https://github.com/molecularsets/moses) and my own , something weird happened, my **FCD Test** value and **FCD TestSF** value is much smaller than your results.
So , why ?

|char-rnn | MOSES| MY OWN RESULT|
|----------|:-------------:|------:|
|FCD (↓) Test | 0.355 | 02616|
|FCD (↓) TestSF | 0.8995 | 0.7881|

**Comment by danpol** [comment]
Hi, @xusworld! I'll rerun the experiment and respond as soon as I get the result to confirm this

**Comment by danpol** [comment]
My results after training for 200 epochs are
```FCD/Test,FCD/TestSF,Filters,Frag/Test,Frag/TestSF,IntDiv,IntDiv2,NP,QED,SA,SNN/Test,SNN/TestSF,Scaf/Test,Scaf/TestSF,logP,model,unique@1000,unique@10000,valid,weight
0.09141197286501779,0.542871095260125,0.9896506216572897,0.99978901552771,0.9983847231176738,0.8565657042706962,0.8506071471914556,0.0003841876390966448,2.8501581030470485e-05,0.0014487681101258976,0.5790276488239685,0.5485751854219958,0.9184270905143336,0.12891313394290216,0.005490995072889415,char_rnn,1.0,0.9994,0.9598,12.197892211531098```
I've launched the training again to check if these results are reproducible. I'll also re-run other models and check if this deviation is due to the changes in library versions.

**Comment by xusworld** [comment]
thanks for your reply @danpol , but in your new results, **FCD/Test = 0.0913, FCD/TestSF = 0.54** , this is much **better** than the results on MOSES benchmark table, so may be you should update your result on 
[MOSES](https://github.com/molecularsets/moses#metrics)?

**Comment by danpol** [comment]
Sure, I'll do it as soon as I get the results from the second run

**Comment by xusworld** [comment]
hi @danpol ,  I noticed that after 200 epochs, almost everything is better(except Scaf/TestSF, from 0.1398 in your original result to 0.1289) and the valid of char-rnn from 0.8088(original value in MOSES) to **0.9598**, which is a huge improvement. But this is also a little confusing,  because now I know that my char-rnn not fully trained under 50 epochs.

**Comment by danpol** [comment]
@xusworld, results are reproducible, see PR #48
