### ISSUE TITLE
Regarding Vocabulary

### ISSUE THREAD

**Issue by meghanakanapaneni** [molecularsets/moses#46]
Sir,for aae model what is the type of vocabulary we should consider.I have text file.How should I convert this to vocabulary which can be used for aae model?

**Comment by danpol** [comment]
Hi, @meghanakanapaneni!

AAE model uses [CharVocab](https://github.com/molecularsets/moses/blob/master/moses/utils.py#L26), and the training script passes a pandas DataFrame with SMILES column to [`get_vocabulary`](https://github.com/molecularsets/moses/blob/master/moses/aae/trainer.py#L232).

If you want to create a vocabulary with a predefined set of characters, you can manually create a CharVocab with [`__init__`](https://github.com/molecularsets/moses/blob/master/moses/utils.py#L35) and pass your characters as a first argument. Then you should save your vocab with `torch.save(vocab, your_vocab_path)`. To train/evaluate the model with your vocabulary, pass `--vocab_save your_vocab_path` to the script.

If you want to create a custom vocabulary (e.g., a custom tokenizer), you can create a class with the same interface as CharVocab and save to a file with `torch.save`. You can then train/evaluate the model similar to the previous case (`--vocab_save your_vocab_path`): this will automatically load an instance of your class and use it during training and evaluation.

**Comment by khlharsh** [comment]
How the Char_Vocab is working can you please sharing some resources??
