### ISSUE TITLE
Long time for training

### ISSUE THREAD

**Issue by meghanakanapaneni** [molecularsets/moses#47]
Sir,it is taking a lot of time for training .I can see no progress in training.I am just training for 100 samples and 1 epoch in pre train and train functions for aae model.Can you please help me with this?What might be the problem sir?

**Comment by danpol** [comment]
Yes, training the model until convergence takes around a week on a high-end GPU

**Comment by xuzhang5788** [comment]
@danpol 
What do you mean " training the model until convergence" ? Is it training one of the models or training all eight models? Thanks
