### ISSUE TITLE
RuntimeError when executing the run.py

### ISSUE THREAD

**Issue by vandan-revanur** [molecularsets/moses#53]
Following the instructions on the readme, I did an End-to-End launch, by running the run.py in the scripts folder. 

Traceback (most recent call last):
  File "run.py", line 208, in <module>
    main(config)
  File "run.py", line 190, in main
    sample_from_model(config, model)
  File "run.py", line 127, in sample_from_model
    sampler_script.main(model, sampler_config)
  File "/content/moses/scripts/moses/scripts/sample.py", line 47, in main
    min(n, config.n_batch), config.max_len
  File "/usr/local/lib/python3.7/site-packages/molsets-0.1.4-py3.7.egg/moses/vae/model.py", line 218, in sample
    i_eos_mask = ~eos_mask & (w == self.eos)
RuntimeError: Expected object of scalar type Byte but got scalar type Bool for argument #2 'other'

How could I resolve this?

**Comment by danpol** [comment]
Hi, @vandan-revanur! What version of PyTorch are you using?

**Comment by vandan-revanur** [comment]
@danpol I am using Pytorch version : 1.1.0. 
PS: I am running the code on Google Colab, if that information helps in some way.

**Comment by danpol** [comment]
@vandan-revanur, please check that you are using PyTorch 1.1.0 and not 1.2.0

**Comment by danpol** [comment]
Hi, @vandan-revanur. I hope the answer above helped you. If you have further questions, feel free to reopen the issue.
