### ISSUE TITLE
Could not find a version that satisfies the requirement torch>=1.1.0

### ISSUE THREAD

**Issue by data-datum** [molecularsets/moses#57]
I have issues with a newer version of PyTorch. 
My version of PyTorch is 1.2.0

**Comment by iwatobipen** [comment]
Hi, I use pytorch 1.2.0 too. How about to try to comment out following line, if you already installed torch.
https://github.com/molecularsets/moses/blob/b94468cab4590ced03a98c26a35d3c1e0647d9c9/setup.py#L16
Thanks,

**Comment by danpol** [comment]
Hi! We'll enable newer versions of PyTorch this week in a separate merge request

**Comment by danpol** [comment]
Hi, @iwatobipen and @data-datum. MOSES should work fine with `torch>=1.1.0` starting from 0.3.1. Please let me know if you experience any troubles with updated dependencies :)

**Comment by iwatobipen** [comment]
Thanks! I will use new version ;)
