### ISSUE TITLE
TypeError: get_all_metrics() got an unexpected keyword argument 'train'

### ISSUE THREAD

**Issue by toushi68** [molecularsets/moses#61]
any modification from last update?
I got an error message from:
###########
python scripts/eval.py --n_jobs 4 --device cuda:0 --test_path data/test.csv --ptest_path data/test_stats.npz --test_scaffolds_path data/test_scaffolds.csv --ptest_scaffolds_path data/test_scaffolds_stats.npz --gen_path checkpoints/organ_generated.csv 
Traceback (most recent call last):
  File "scripts/eval.py", line 87, in <module>
    main(config)
  File "scripts/eval.py", line 42, in main
    train=train)
TypeError: get_all_metrics() got an unexpected keyword argument 'train'
############
It was OK before.
Oh Happy 1024!

**Comment by danpol** [comment]
Hi, @toushi68! I think you should update to molsets version 0.2

**Comment by danpol** [comment]
Hi, @toushi68, is the problem solved? I'm closing this issue, but feel free to reopen it if the issue remains.
