### ISSUE TITLE
Continue to have errors. Request Help. Please see attached 3 txt files.

### ISSUE THREAD

**Issue by webservicereco** [molecularsets/moses#68]
January 15, 2020... Simon, Thanks for the help so far. I have been able to download and install all packages from the new fork: https://github.com/SeemonJ/moses which you shared on Dec 21, 2019. Thanks for that. I am now facing errors listed in attached 3 txt files. Request your help to fix these errors.
[Errro Running Moses_15Jan2020.txt](https://github.com/molecularsets/moses/files/4066910/Errro.Running.Moses_15Jan2020.txt)
[Errro Running sh scripts_run_all_models.txt](https://github.com/molecularsets/moses/files/4066912/Errro.Running.sh.scripts_run_all_models.txt)
[List of installed packages.txt](https://github.com/molecularsets/moses/files/4066914/List.of.installed.packages.txt)

**Comment by danpol** [comment]
Hi, @webservicereco! I was able to run LatentGAN training without any problems. Regarding the attached files, the first one says `python: command not found`. You should check if your environment is configured correctly and Python is installed. Regarding the second one, I'm not sure that the TF build we recommend will run on Windows. I suggest running the experiments on Linux machine or using a provided Docker image with Ubuntu 16.04

**Comment by danpol** [comment]
Hi, @webservicereco. I hope the answer above helped you. If you have further questions, feel free to reopen the issue.
