### ISSUE TITLE
where is ddc_pub?

### ISSUE THREAD

**Issue by toushi68** [molecularsets/moses#69]
Hi,
Did you forget to tell us how to specify "ddc_pub"?
in 
from .model import LatentGAN
moses/latentgan/model.py", line 4  <module>
from ddc_pub import ddc_v3 as ddc

**Comment by toushi68** [comment]
is it this one?
https://github.com/pcko1/Deep-Drug-Coder

**Comment by danpol** [comment]
Hi! You can install all the dependencies using the installation script: https://github.com/molecularsets/moses/blob/master/install_moses.sh

**Comment by danpol** [comment]
Hi, @toushi68! I hope the answer above helped you. If you have further questions, feel free to reopen the issue.
