### ISSUE TITLE
multi gpu experiments

### ISSUE THREAD

**Issue by trinayan** [molecularsets/moses#83]
Hi,

Have there been any effort in scaling the models to multi-GPU systems for training?. I am not a molecular domain expert. I am curious if there are situations where using multi-GPU would help for the models used in the benchmark suite. 

Best,
Trinayan

**Comment by danpol** [comment]
Hi, @trinayan!

We did not implement multi-GPU training for the baselines, but it could be profitable for reducing the training time for some models.

**Comment by trinayan** [comment]
Got it. Thank you for the info
