### ISSUE TITLE
Suggesting Internal Diversity Metric

### ISSUE THREAD

**Issue by lilleswing** [molecularsets/moses#9]
Just a suggestion from other people in industry doing this kind of work.

The internal diversity metric as of right now is calculating the mean absolute error of the distance matrix.
![selection_445](https://user-images.githubusercontent.com/1225605/49528769-a60b5e80-f882-11e8-8427-3d7a582e1935.png)

I would suggest taking the RMSE instead.
![selection_444](https://user-images.githubusercontent.com/1225605/49528669-68a6d100-f882-11e8-8592-de8276a38805.png)

This will more heavily punish skewed datasets where all but a few compounds are highly similar with one compound being very different.  We are using the second metric internally.

**Comment by danpol** [comment]
Added as "IntDiv2" (#14). We'll update the results table soon.
