### ISSUE TITLE
moses.get_dataset('train') -> BadGzipFile: Not a gzipped file (b've')

### ISSUE THREAD

**Issue by UnixJunkie** [molecularsets/moses#96]
Same for 'test' and 'test_scaffolds'.

**Comment by UnixJunkie** [comment]
Can I get the corresponding SMILES strings for each dataset in another way?

**Comment by UnixJunkie** [comment]
Ok, under data/ probably.

**Comment by UnixJunkie** [comment]
git lfs was not installed...

**Comment by UnixJunkie** [comment]
Ok, my mistake.
Not having git lfs installed doesn't clone the repository correctly.
You could have stored xz -9 compressed .smi files in your repository though.

**Comment by HandanDiana** [comment]
Hi @UnixJunkie, could you please explain more details about how to deal with this issue (moses.get_dataset('train') -> BadGzipFile: Not a gzipped file (b've')) ultimately? Cause, I also encounter this problem. Thanks!
